import { OrderRow } from './orders.types';

export const ordersMock: OrderRow[] = [
  {
    key: '1',
    patient: 'Sierra Young',
    product: 'DAFO 3 Softy',
    orderedDate: '12/05/2025',
    shipDate: '12/07/2025',
    soNumber: 'SO12368',
    poNumber: 'PC-23458',
    orderedBy: 'Dr. Ethan Carter',
    status: 'Received',
    statusKey: 'received',
  },
  {
    key: '2',
    patient: 'Liam Smith',
    product: 'Polyethylene',
    orderedDate: '12/02/2025',
    shipDate: '12/06/2025',
    soNumber: 'SO12587',
    poNumber: 'PC-23647',
    orderedBy: 'Dr. Sarah Lee',
    status: 'Received',
    statusKey: 'received',
  },
  {
    key: '3',
    patient: 'Emma Johnson',
    product: 'Bilateral',
    orderedDate: '12/01/2025',
    shipDate: '12/05/2025',
    soNumber: 'SO12450',
    poNumber: 'PC-23689',
    orderedBy: 'Dr. Robert Wilson',
    status: 'Processed',
    statusKey: 'production',
  },
  {
    key: '4',
    patient: 'Noah Davis',
    product: 'DAFO 3.5',
    orderedDate: '12/04/2025',
    shipDate: '12/07/2025',
    soNumber: 'SO12499',
    poNumber: 'PC-23670',
    orderedBy: 'Dr. Angela Martin',
    status: 'Production',
    statusKey: 'production',
  },
  {
    key: '5',
    patient: 'Olivia Garcia',
    product: 'Bilateral',
    orderedDate: '12/03/2025',
    shipDate: '12/06/2025',
    soNumber: 'SO12510',
    poNumber: 'PC-23710',
    orderedBy: 'Dr. Cindy Perez',
    status: 'Processed',
    statusKey: 'production',
  },
  {
    key: '6',
    patient: 'Ava Martinez',
    product: 'Polyethylene',
    orderedDate: '12/08/2025',
    shipDate: '12/12/2025',
    soNumber: 'SO12601',
    poNumber: 'PC-23801',
    orderedBy: 'Dr. Emily Rose',
    status: 'Received',
    statusKey: 'received',
  },
  {
    key: '7',
    patient: 'James Rodriguez',
    product: 'DAFO 3 Softy',
    orderedDate: '12/10/2025',
    shipDate: '12/14/2025',
    soNumber: 'SO12640',
    poNumber: 'PC-23845',
    orderedBy: 'Dr. Brian Kim',
    status: 'Production',
    statusKey: 'production',
  },
  {
    key: '8',
    patient: 'Sophia Hernandez',
    product: 'Bilateral',
    orderedDate: '11/29/2025',
    shipDate: '12/03/2025',
    soNumber: 'SO12290',
    poNumber: 'PC-23345',
    orderedBy: 'Dr. Lisa Wong',
    status: 'Production',
    statusKey: 'production',
  },
];


